apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-httpcache
  namespace: varnish-cache
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  verbs:
  - watch
  - get